server:
  context-path: /
  port: 6060
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_film
    username: root
    password: mac123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  resources:
      static-locations: classpath:/static/,classpath:/templates/
# 需要加上，才能打包到jar里面
  mvc:
    static-path-pattern: /**



# 图片保存的地址
imageFilePath: /Users/zhouli/mygithub/film/src/main/webapp/static/filmImage/
